"""create orders

Revision ID: 0d50cb7d4f3e
Revises: a19dda2665d9
Create Date: 2025-04-08 02:03:14.971504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d50cb7d4f3e'
down_revision: Union[str, None] = 'a19dda2665d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('orders',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('total_discounted_amount', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('coupon_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitem',
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('header', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_image_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('sku', 'order_id')
    )
    op.add_column('cart', sa.Column('order_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'cart', ['order_id'])
    op.create_foreign_key(None, 'cart', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_column('cart', 'order_id')
    op.drop_table('orderitem')
    op.drop_table('orders')
    op.drop_table('coupon')
    # ### end Alembic commands ###
